# Generated by Django 3.2 on 2021-04-07 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('label', models.CharField(max_length=255, verbose_name='Nom du groupe')),
            ],
            options={
                'verbose_name': "Groupe de l'utilisateur",
                'verbose_name_plural': "Groupes de l'utilisateur",
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('lastname', models.CharField(max_length=255, verbose_name='Prénom')),
                ('firstname', models.CharField(max_length=255, verbose_name='Nom')),
                ('custom_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userprofiles', to='userprofile.usercustomgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['firstname'],
            },
        ),
    ]
