# Generated by Django 3.2 on 2021-04-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=12)),
                ('adress', models.CharField(max_length=255)),
                ('endDate', models.DateField(auto_now_add=True, verbose_name='Date de fin')),
                ('price', models.IntegerField(verbose_name='prix')),
                ('ref', models.CharField(max_length=255, verbose_name="Référence de l'offre")),
                ('prospecting', models.BooleanField(verbose_name='en prospection')),
                ('ground', models.FloatField(verbose_name='surface')),
                ('creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('comment', models.CharField(max_length=512, verbose_name="commentaire sur l'offre")),
            ],
            options={
                'verbose_name': 'Prospecté',
                'verbose_name_plural': 'Prospectés',
            },
        ),
    ]
