# Generated by Django 3.2 on 2021-04-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospecting', '0002_negociator_route'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='negociator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospecting.negociator'),
        ),
    ]
