# Generated by Django 3.1.7 on 2021-04-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20210408_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='tel',
            new_name='phone',
        ),
    ]
