# Generated by Django 3.2 on 2021-04-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospecting', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negociator',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userprofile.userprofile')),
                ('color', models.CharField(default='black', max_length=10)),
            ],
            options={
                'verbose_name': 'Négociateur',
                'verbose_name_plural': 'Négociateurs',
            },
            bases=('userprofile.userprofile',),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('startLat', models.FloatField(verbose_name='Point de départ lattitude')),
                ('startLng', models.FloatField(verbose_name='Point de départ longitude')),
                ('endLat', models.FloatField(verbose_name="Point d'arrivé lattitude")),
                ('endLng', models.FloatField(verbose_name="point d'arrivé longitude")),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospecting.map')),
                ('negociator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospecting.negociator')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
    ]
