# Generated by Django 3.1.7 on 2021-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(default='test', max_length=255)),
                ('firstname', models.CharField(default='test', max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(default='test@test.fr', max_length=254)),
                ('creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('comment', models.CharField(max_length=1024)),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lng', models.FloatField(verbose_name='longitude')),
            ],
        ),
    ]
